from setuptools import setup, find_packages

setup(
    name="gemvise",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        'numpy>=1.21.0',
        'transformers>=4.30.0',
        'torch>=2.0.0',
        'sentence-transformers>=2.2.0',
        'sqlalchemy>=2.0.0',
        'apscheduler>=3.10.0',
        'python-dotenv>=1.0.0',
        'langchain>=0.0.300',
        'openai>=1.0.0',
        'anthropic>=0.5.0',
        'fastapi>=0.100.0',
        'uvicorn>=0.23.0',
        'chromadb>=0.4.0',
        'faiss-cpu>=1.7.4',
        'pydantic>=2.0.0',
        'graphene>=3.3.0',
        'aiohttp>=3.8.0',
        'PyPDF2>=3.0.0',
        'beautifulsoup4>=4.12.0',
        'scholarly>=1.7.0',
        'selenium>=4.10.0',
        'webdriver_manager>=4.0.0'
    ],
    python_requires='>=3.9',
    author="GemVise Team",
    author_email="dev@gemvise.ai",
    description="A quantum-inspired expert system",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/bdizha/gemvise",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
    ],
)
